remote_theme: the-256-foundation/hacker-theme
title: Mujina Firmware
description: Open Source Bitcoin Mining Firmware
github:
  repository_url: https://github.com/The-256-Foundation/Mujina-Mining-Firmware-website
  owner_url: https://256foundation.org
